# Generated by Django 4.0.4 on 2022-05-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0003_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
